import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar"
const inter = Inter({ subsets: ["latin"] });
import { NextUIProvider } from "@nextui-org/system";
import { ThemeProvider } from "@/components/theme-provider";
import { NavbarDemo, } from "@/components/floating-nav";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={inter.className}>

        <ThemeProvider attribute="class" defaultTheme="system" >
          <div className=""><NavbarDemo /></div>
          {/* <div className=""><Navbar /></div> */}
          {/* <div className=""><TestingComp/></div> */}
          <div className="absolute w-full top-24">
            {children}
          </div>

          {/* <div className="flex flex-col w-[100vw] h-[100vh]">
            <div className=""><NavbarDemo /></div>
            <span>
              {children}
            </span>
          </div> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
