import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
const inter = Inter({ subsets: ["latin"] });
import { NextUIProvider } from "@nextui-org/system";
import { ThemeProvider } from "@/components/theme-provider";
import { NavbarDemo } from "@/components/floating-nav";
import { ReduxProvider } from "@/redux/provider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { useTheme } from "next-themes";

export const metadata: Metadata = {
  title: "Minor Project Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <ThemeProvider attribute="class" defaultTheme="system">
            <ToastContainer theme={"dark"} />
            <NavbarDemo />
            <div className="absolute w-full top-24">{children}</div>
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
